### ISSUE TITLE
Personal Message Length with Donation Notification

### ISSUE THREAD

**Issue by GPREAPER** [TNotifier/Issues#16]
The personal message that people can leave with their donations that shows up with the notification gets cut off if the message is longer than the size of the notification. Is there a word wrap that can be implemented?

**Comment by Oyed** [comment]
There is CSS that can be added to do this; it's not applied by default due to how it'll make the alert increase in height to fit more text on new lines, which can mess up some setups that aren't set up for that sort of thing.

I'll create an FAQ entry with the CSS to get this working tomorrow. I'll update this issue when I have more news!

**Comment by GPREAPER** [comment]
Ok thank you :D

**Comment by Oyed** [comment]
Putting this off for now - looking at the CSS it will be complicated to explain what it does as it'll require modification on a per-Widget basis. Will revisit this in the future.
