### ISSUE TITLE
Media & Tokens Tool Tip Different then Notifications

### ISSUE THREAD

**Issue by WLWarfare** [TNotifier/Issues#7]
When you hover over media and tokens the tool tip that appears is white text with a black box. However the notifications icon tool tip is different. Not sure if intentional or not.

**Comment by Oyed** [comment]
Due to Notifications having a Dropdown which the tooltip covers initially, you can't see this on Alpha as there is no dropdown for notifications (When there are no notifications, the Dropdown just doesn't show)

I'll leave this for now, as I'll add a dropdown even when there are no notifications just so there's no confusion.

**Comment by Oyed** [comment]
Fixed - dropdown added if there are no notifications indicating so.
